### ISSUE TITLE
Installation on Raspberrypi 4 fails installing tensorflow

### ISSUE THREAD

**Issue by thatguyinoz** [connervieira/Predator#3]
**Bug Description:**
Installation on Raspberrypi 4 fails when trying to install tensorflow

**Steps To Reproduce:**
After general system updates and upgrades to latest version of all packages, when following the installation instructions as per DOCUMENTATION.md; Step 1
issuing the command:
`pi@hexham:~/Predator $ sudo pip3 install tensorflow`
returns this error:
```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement tensorflow
ERROR: No matching distribution found for tensorflow
```

**Expected Behavior:**
installation of tensorflow package should succeed

**Applicable Screenshots And Logs:**
NA

**Setup Information:**
Raspberry pi 4  running "Bullseye"
Linux hexham 5.15.84-v7l+ #1613 SMP Thu Jan 5 12:01:26 GMT 2023 armv7l GNU/Linux

**Additional Information:**
Some general searches of the Internet seem to point to this being  a conflict with python3.9. but this is beyond my level of skill.
Any assistance getting past this point would be appreciated.

**Comment by connervieira** [comment]
I tend to find some weird behavior occurs when running Python as superuser. Do you find the same problem occurs when running `pip3 install tensorflow`, without `sudo`?

**Comment by connervieira** [comment]
I'm going to close this issue for now, because I can't seem to recreate the issue using the official documentation.
