### ISSUE TITLE
Raspberry Pi camera compatability

### ISSUE THREAD

**Issue by timothylidede** [connervieira/Predator#4]
**Problem with the ALPR library**
When running the app on rpi4, I get this message on the console:
Image file not found: /home/pi/Predator/realtime_image.jpg
The JSON data returned by the ALPR process is malformed. This likely means there's a problem with the ALPR library.

what could be the cause of this

**Comment by mistaken4kings** [comment]
It's because there's no way to use raspberry pi camera as the default camera, could this be changed?

**Comment by connervieira** [comment]
I'm unfamiliar with the Raspberry Pi camera, but you can specify a camera device for FSWebCam to use in the configuration.

It's possible the Raspberry Pi camera doesn't operate as a generic camera though. If that's the case, is there another command utility that the Raspberry Pi uses to capture stills from the camera? I might be able to add it as a camera back-end option.

**Comment by connervieira** [comment]
As a side note, I'm currently developing an alternative version of OpenALPR called Phantom, designed specifically for use in Predator. This modified version will be able to feed back more descriptive errors in order to avoid these vague error messages.

**Comment by khanfar** [comment]
does Phantom available ?
