### ISSUE TITLE
[FEATURE] Multiple license plate formats

### ISSUE THREAD

**Issue by larmicfre** [connervieira/Predator#6]
**Feature Description**:
Extend the capabilities of Predator to recognize and process multiple license plate formats.

**Usage**:
Users should have the ability to specify multiple license plate formats pertinent to their region or requirements. By supporting multiple formats, Predator would become significantly more versatile and useful for regions with diverse license plate structures.

**Comment by connervieira** [comment]
This is a great idea, and is completely feasible. I'm currently busy with other projects and responsibilities, but I've added it to the to-do list, and it shouldn't be too difficult to add.
